export interface SurveyForm {
    question1_0,
    question1_1,
    question1_2,
    question1_3,
    question1_4,
    question1_5,
    question1_6,
    question1_7,
    question1_8,

    question2_0,
    question2_1,
    question2_2,
    question2_3,

    question3_0,
    question3_1,
    question3_2,

    question4,
    question5,
    question6,
    question7: number,
    question8,
    question9,
    question10,
    question11,
}

export interface RecommendationHandler {
    regionIds: number[],
    regionIdsString?: string,
    localeIds: number[],
    localeIdsString?: string,
    costRange: string,
    costRangeString?: string,
    studentSizeRange: string,
    studentSizeString?: string,
    menOnly: number,
    womenOnly: number,
    schoolTypeString?: string,
    ownershipIds: number[],
    ownershipString?: string,
    degreeIds: number[],
    degreeIdsString?: string,
    satScoreRange?: number,
    satScoreString?: string,
    actScoreRange?: number,
    actScoreString?: string
}